            <a href="<?php echo siteUrl()?>" target='_blank'>微博首页</a>
			<a href="<?php echo siteUrl('cp/welcome')?>" target="weShuo">系统设置</a>
			<a href="<?php echo siteUrl('ucp/user')?>" target="weShuo">用户管理</a>
			<a href="<?php echo siteUrl('sys/score')?>" target="weShuo">积分管理</a>
			<a href="<?php echo siteUrl('tcp/tag')?>" target="weShuo">话题管理</a>
			<a href="<?php echo siteUrl('tcp/topic')?>" target="weShuo">微博管理</a>
			<a href="<?php echo siteUrl('tcp/group')?>" target="weShuo">群组管理</a>
			<a href="<?php echo siteUrl('sys/link')?>" target="weShuo">友情连接</a>
			<a href="<?php echo siteUrl('sys/news')?>" target="weShuo">新闻公告</a>
			<a href="<?php echo siteUrl('tcp/comment')?>" target="weShuo">评论管理</a>
            <a href="<?php echo siteUrl('ext')?>" target="weShuo">扩展</a>
            <a href="<?php echo siteUrl('sys/logout')?>" target="parent">退出系统</a>
